version: '3.9'
services:
  comfyui:
    image: nexmoe/serverless-comfyui:0.5
    ports:
      - "3008:3000"
      - "8189:8180"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia # 使用 NVIDIA GPU 驱动
              count: 1 # 预留的 GPU 数量
              capabilities: [ gpu ] # 指定 GPU 功能
